version: 2.1.0
services:
  # sql-service:
  #   build:
  #     context: ./streamingSQL
  #     dockerfile: Dockerfile
  #   environment:
  #     - DB_USER=user
  #     - DB_PASSWORD=password
  #     - DB_ADDR=db
  #     - DB_PORT=5432
  demo:
    build:
      context: ./demo
      dockerfile: Dockerfile
    command: npm run start:dev
    ports:
      - "3000:3000"
    depends_on:
      - db
    env_file:
      - .env
    environment:
      - DATABASE_URL=${DATABASE_URL}
  db:
    build:
      context: ./postgres
      dockerfile: ./Dockerfile
    command:
      - "postgres"
      - "-c"
      - "wal_level=logical"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=user
      - POSTGRES_DB=postgres
    volumes:
      - pgVolume:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  pgVolume:
